using UnityEngine;
using UnityEngine.InputSystem;

public class PlayerController : MonoBehaviour
{
    public InputActionReference moveAction;
    public CharacterController charCon;

    public float moveSpeed;

    private float ySpeed;

    public InputActionReference jumpAction;
    public float jumpForce;

    public InputActionReference lookAction;
    private float horiRot, vertRot;
    public float lookSpeed;
    public Camera theCam;
    public float minLookAngle, maxLookAngle;

    public LayerMask whatIsStock;
    public float interactionRange;

    private GameObject heldPickUp;
    public Transform holdPoint;

    public float throwForce;

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        Cursor.lockState = CursorLockMode.Locked;
    }

    // Update is called once per frame
    void Update()
    {
        Vector2 lookInput = lookAction.action.ReadValue<Vector2>();

        horiRot += lookInput.x * Time.deltaTime * lookSpeed;
        transform.rotation = Quaternion.Euler(0f, horiRot, 0f);

        vertRot -= lookInput.y * Time.deltaTime * lookSpeed;
        vertRot = Mathf.Clamp(vertRot, minLookAngle, maxLookAngle);
        theCam.transform.localRotation = Quaternion.Euler(vertRot, 0f, 0f);

        Vector2 moveInput = moveAction.action.ReadValue<Vector2>();

        //Debug.Log(moveInput);

        //transform.position = transform.position + new Vector3(
        //moveInput.x * Time.deltaTime * moveSpeed, 0f, moveInput.y * Time.deltaTime * moveSpeed);

        //Vector3 moveAmount = new Vector3(moveInput.x, 0f, moveInput.y);

        Vector3 vertMove = transform.forward * moveInput.y;
        Vector3 horiMove = transform.right * moveInput.x;

        //Debug.Log(vertMove + "-" +  horiMove);

        Vector3 moveAmount = horiMove + vertMove;

        moveAmount = moveAmount.normalized;

        moveAmount = moveAmount * moveSpeed;

        if(charCon.isGrounded == true)
        {
            ySpeed = 0f;

            if (jumpAction.action.WasPressedThisFrame())
            {
                ySpeed = jumpForce;
            }
        }

        ySpeed += (Physics.gravity.y * Time.deltaTime);

        moveAmount.y = ySpeed;

        charCon.Move(moveAmount * Time.deltaTime);

        //check for pickUp
        Ray ray = theCam.ViewportPointToRay(new Vector3(.5f, .5f, 0f));
        RaycastHit hit;

        /* if (Physics.Raycast(ray, out hit, interactionRange, whatIsStock))
        {
            Debug.Log("I see a pickUp");
        }
        else
        {
            Debug.Log("I can't see anything!");
        } */

        if (Mouse.current.leftButton.wasPressedThisFrame)
        {
            if (Physics.Raycast(ray, out hit, interactionRange, whatIsStock))
            {
                //Debug.Log("I see a pickUp");

                heldPickUp = hit.collider.gameObject;
                heldPickUp.transform.SetParent(holdPoint);
                heldPickUp.transform.localPosition = Vector3.zero;
                heldPickUp.transform.localRotation = Quaternion.identity;

                heldPickUp.GetComponent<Rigidbody>().isKinematic = true;
            }
        }

        if (Mouse.current.rightButton.wasPressedThisFrame)
        {
            Rigidbody pickUpRB = heldPickUp.GetComponent<Rigidbody>();
            pickUpRB.isKinematic = false;
            pickUpRB.AddForce(theCam.transform.forward * throwForce, ForceMode.Impulse); 

            heldPickUp.transform.SetParent(null);
            heldPickUp = null;
        }
    }
}
